<template>
  <main class="flex-1 py-12">
    <ContentProse>
      <h2>About Bricks &amp; Dragons</h2>
      <p>
        This web app provides instructions of custom built brick modules for a
        modular micro-scale LEGO® dungeon system. Each module can be added to a
        wanted list in XML format. All LEGO® parts can then be ordered on
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://www.bricklink.com/v2/wanted/upload.page?utm_content=subnav"
          >bricklink</a
        >
        by pasting the XML data into the form field provided (requires a
        bricklink account). This service is free of charge.
      </p>
      <p>
        I maintain this project as a hobby. Please note that I cannot guarantee
        the validity of the generated wanted list. Please check carefully before
        buying parts on bricklink!
      </p>
      <nuxt-picture
        loading="lazy"
        width="1600"
        height="1200"
        quality="80"
        src="/images/themes-overview.png"
        alt="Bricks &amp; Dragons themes"
        sizes="xs:100vw lg:1200"
      />
      <small class="block -mt-16 text-center opacity-75"
        >An earlier version of the modules</small
      >

      <h3>Disclaimer</h3>
      <p>
        Bricks &amp; Dragons is not affiliated with The LEGO Group. LEGO® is a
        trademark of The LEGO Group of companies which does not in anyway
        sponsor, authorize, or endorse this content. All other original logos
        and/or brands used are property of their respective owners.
        <br /><br />
        <strong>Content</strong>: The author reserves the right not to be
        responsible for the topicality, correctness, completeness or quality of
        the information provided. Liability claims regarding damage caused by
        the use of any information provided, including any kind of information
        which is incomplete or incorrect,will therefore be rejected. All offers
        are not-binding and without obligation. Parts of the pages or the
        complete publication including all offers and information might be
        extended, changed or partly or completely deleted by the author without
        separate announcement. <br /><br />
        <strong>Referrals and links</strong>: The author is not responsible for
        any contents linked or referred to from his pages - unless he has full
        knowledge of illegal contents and would be able to prevent the visitors
        of his site fromviewing those pages. If any damage occurs by the use of
        information presented there, only the author of the respective pages
        might be liable, not the one who has linked to these pages. Furthermore
        the author is not liable for any postings or messages published by users
        of discussion boards, guestbooks or mailinglists provided on his page.
        <br /><br />
        <strong>Copyright</strong>: The author intended not to use any
        copyrighted material for the publication or, if not possible, to
        indicate the copyright of the respective object. The copyright for any
        material created by the author is reserved. Any duplication or use of
        objects such as images, diagrams, sounds or texts in other electronic or
        printed publications is not permitted without the author's agreement.
        <br /><br />
        <strong>Privacy</strong>: This website uses Google Analytics, a web
        analytics service provided by Google, Inc. ("Google"). Google Analytics
        uses "cookies", which are text files placed on your computer, to help
        the website analyze how users use the site. The information generated by
        the cookie about your use of the website (including your IP address)
        will be transmitted to and stored by Google on servers in the United
        States . Google will use this information for the purpose of evaluating
        your use of the website, compiling reports on website activity for
        website operators and providing other services relating to website
        activity and internet usage. Google may also transfer this information
        to third parties where required to do so by law, or where such third
        parties process the information on Google's behalf. Google will not
        associate your IP address with any other data held by Google. You may
        refuse the use of cookies by selecting the appropriate settings on your
        browser, however please note that if you do this you may not be able to
        use the full functionality of this website. By using this website, you
        consent to the processing of data about you by Google in the manner and
        for the purposes set out above. <br /><br />
        <strong>Privacy policy</strong>: If the opportunity for the input of
        personal or business data (email addresses, name, addresses) is given,
        the input of these data takes place voluntarily. The use and payment of
        all offered services are permitted - if and so far technically possible
        and reasonable - without specification of any personal data or under
        specification of anonymized data or an alias. The use of published
        postal addresses, telephone or fax numbers and email addresses for
        marketing purposes is prohibited, offenders sending unwanted spam
        messages will be punished. <br /><br />
        <strong>Legal validity of this disclaimer</strong>: This disclaimer is
        to be regarded as part of the internet publication which you were
        referred from. If sections or individual terms of this statement are not
        legal or correct, the content or validity of the other parts remain
        uninfluenced by this fact.
      </p>
      <h2>License</h2>
      <p>
        The content of this website is released under the OGL 1.0a license
        agreement.
      </p>
      <p>
        THIS LICENSE IS APPROVED FOR GENERAL USE. PERMISSION TO DISTRIBUTE THIS
        LICENSE IS MADE BY WIZARDS OF THE COAST!
      </p>

      <h3>OPEN GAME LICENSE Version 1.0a</h3>
      <p>
        The following text is the property of Wizards of the Coast, Inc. and is
        Copyright 2000 Wizards of the Coast, Inc ("Wizards"). All Rights
        Reserved.
      </p>
      <ul class="mb-8">
        <li>
          1. Definitions: (a)"Contributors" means the copyright and/or trademark
          owners who have contributed Open Game Content; (b)"Derivative
          Material" means copyrighted material including derivative works and
          translations (including into other computer languages), potation,
          modification, correction, addition, extension, upgrade, improvement,
          compilation, abridgment or other form in which an existing work may be
          recast, transformed or adapted; (c) "Distribute" means to reproduce,
          license, rent, lease, sell, broadcast, publicly display, transmit or
          otherwise distribute; (d)"Open Game Content" means the game mechanic
          and includes the methods, procedures, processes and routines to the
          extent such content does not embody the Product Identity and is an
          enhancement over the prior art and any additional content clearly
          identified as Open Game Content by the Contributor, and means any work
          covered by this License, including translations and derivative works
          under copyright law, but specifically excludes Product Identity. (e)
          "Product Identity" means product and product line names, logos and
          identifying marks including trade dress; artifacts; creatures
          characters; stories, storylines, plots, thematic elements, dialogue,
          incidents, language, artwork, symbols, designs, depictions,
          likenesses, formats, poses, concepts, themes and graphic, photographic
          and other visual or audio representations; names and descriptions of
          characters, spells, enchantments, personalities, teams, personas,
          likenesses and special abilities; places, locations, environments,
          creatures, equipment, magical or supernatural abilities or effects,
          logos, symbols, or graphic designs; and any other trademark or
          registered trademark clearly identified as Product identity by the
          owner of the Product Identity, and which specifically excludes the
          Open Game Content; (f) "Trademark" means the logos, names, mark, sign,
          motto, designs that are used by a Contributor to identify itself or
          its products or the associated products contributed to the Open Game
          License by the Contributor (g) "Use", "Used" or "Using" means to use,
          Distribute, copy, edit, format, modify, translate and otherwise create
          Derivative Material of Open Game Content. (h) "You" or "Your" means
          the licensee in terms of this agreement.
        </li>
        <li>
          2. The License: This License applies to any Open Game Content that
          contains a notice indicating that the Open Game Content may only be
          Used under and in terms of this License. You must affix such a notice
          to any Open Game Content that you Use. No terms may be added to or
          subtracted from this License except as described by the License
          itself. No other terms or conditions may be applied to any Open Game
          Content distributed using this License.
        </li>
        <li>
          3. Offer and Acceptance: By Using the Open Game Content You indicate
          Your acceptance of the terms of this License.
        </li>
        <li>
          4. Grant and Consideration: In consideration for agreeing to use this
          License, the Contributors grant You a perpetual, worldwide,
          royalty-free, non-exclusive license with the exact terms of this
          License to Use, the Open Game Content.
        </li>
        <li>
          5.Representation of Authority to Contribute: If You are contributing
          original material as Open Game Content, You represent that Your
          Contributions are Your original creation and/or You have sufficient
          rights to grant the rights conveyed by this License.
        </li>
        <li>
          6.Notice of License Copyright: You must update the COPYRIGHT NOTICE
          portion of this License to include the exact text of the COPYRIGHT
          NOTICE of any Open Game Content You are copying, modifying or
          distributing, and You must add the title, the copyright date, and the
          copyright holder's name to the COPYRIGHT NOTICE of any original Open
          Game Content you Distribute.
        </li>
        <li>
          7. Use of Product Identity: You agree not to Use any Product Identity,
          including as an indication as to compatibility, except as expressly
          licensed in another, independent Agreement with the owner of each
          element of that Product Identity. You agree not to indicate
          compatibility or co-adaptability with any Trademark or Registered
          Trademark in conjunction with a work containing Open Game Content
          except as expressly licensed in another, independent Agreement with
          the owner of such Trademark or Registered Trademark. The use of any
          Product Identity in Open Game Content does not constitute a challenge
          to the ownership of that Product Identity. The owner of any Product
          Identity used in Open Game Content shall retain all rights, title and
          interest in and to that Product Identity.
        </li>
        <li>
          8. Identification: If you distribute Open Game Content You must
          clearly indicate which portions of the work that you are distributing
          are Open Game Content.
        </li>
        <li>
          9. Updating the License: Wizards or its designated Agents may publish
          updated versions of this License. You may use any authorized version
          of this License to copy, modify and distribute any Open Game Content
          originally distributed under any version of this License.
        </li>
        <li>
          10. Copy of this License: You MUST include a copy of this License with
          every copy of the Open Game Content You Distribute.
        </li>
        <li>
          11. Use of Contributor Credits: You may not market or advertise the
          Open Game Content using the name of any Contributor unless You have
          written permission from the Contributor to do so.
        </li>
        <li>
          12. Inability to Comply: If it is impossible for You to comply with
          any of the terms of this License with respect to some or all of the
          Open Game Content due to statute, judicial order, or governmental
          regulation then You may not Use any Open Game Material so affected.
        </li>
        <li>
          13. Termination: This License will terminate automatically if You fail
          to comply with all terms herein and fail to cure such breach within 30
          days of becoming aware of the breach. All sublicenses shall survive
          the termination of this License.
        </li>
        <li>
          14. Reformation: If any provision of this License is held to be
          unenforceable, such provision shall be reformed only to the extent
          necessary to make it enforceable.
        </li>
        <li>
          15. COPYRIGHT NOTICE Open Game License v 1.0a Copyright 2000, Wizards
          of the Coast, Inc.
        </li>
      </ul>

      <p>
        System Reference Document Copyright 2000-2003, Wizards of the Coast,
        Inc.; Authors Jonathan Tweet, Monte Cook, Skip Williams, Rich Baker,
        Andy Collins, David Noonan, Rich Redman, Bruce R. Cordell, John D.
        Rateliff, Thomas Reid, James Wyatt, based on original material by E.
        Gary Gygax and Dave Arneson.
      </p>

      <p>
        Bricks & Dragons @ 2023; Author: Robin Kuprella. <br />
        END OF LICENSE
      </p>

      <h3>Legal Notice</h3>
      <ul class="mb-8">
        <li>Robin C. Kuprella</li>
        <li>Hövenerwiese 7</li>
        <li>45149 Essen</li>
        <li>Germany</li>
        <li>
          Mail:
          <a href="mailto:bricksndragons@gmail.com">bricksndragons@gmail.com</a>
        </li>
      </ul>
      <p>
        <small>
          Built with Nuxt and Tailwind CSS
        </small>
        <svg
          class="inline w-4 h-4 text-red-600"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </p>
    </ContentProse>
  </main>
</template>

<script>
export default {
  head() {
    return {
      title: "About - Bricks & Dragons",
      meta: [
        // hid is used as unique identifier. Do not use `vmid` for it as it will not work
        {
          hid: "description",
          name: "description",
          content:
            "About Bricks & Dragons - A modular micro-scale LEGO® dungeon system"
        }
      ]
    };
  }
};
</script>
